### ISSUE TITLE
Arrays and * operator in experiment description

### ISSUE THREAD

**Issue by FrancescoRusin** [ericmedvet/2dmrsim#4]
Implement the union of two separately defined arrays, for example:
`(s = [N; E; S; W]) * [sim.sensor.sa()] + (a = [0.0; 180.0]) * [sim.sensor.d(r = 1.0)]`
to get the equivalent of:
`[sim.sensor.sa(s = N); sim.sensor.sa(s = E); sim.sensor.sa(s = S); sim.sensor.sa(s = W); sim.sensor.d(a = 0.0; r = 1.0); sim.sensor.d(a = 180.0; r = 1.0)]`

Also, extend the `*` operator to multiple functions with identical arguments, for example:
`(s = [N; E; S; W]) * [sim.sensor.sa(); sim.sensor.sc()]`
to get the equivalent of:
`[sim.sensor.sa(s = N); sim.sensor.sa(s = E); sim.sensor.sa(s = S); sim.sensor.sa(s = W); sim.sensor.sc(s = N); sim.sensor.sc(s = E); sim.sensor.sc(s = S); sim.sensor.sc(s = W)]`

Lastly, the current version does not support the product for array fields, for example:
`(sensors = [[sim.sensor.ar()]; [sim.sensor.a(); sim.sensor.ar()]]) * [sim.agent.numIndependentVoxel(function = sim.function.mlp())]`
does not produce an array of two `numIndependentVoxel` with sensors `[sim.sensor.ar()]` and `[sim.sensor.a(); sim.sensor.ar()]`, simply throwing an exception instead; single external assignment, like:
`(sensors = [sim.sensor.ar(); sim.sensor.a()]) * [sim.agent.numIndependentVoxel(function = sim.function.mlp())]`
does not work either, as it creates two `numIndependentVoxel` with a single sensor instead of one with two sensors.

**Comment by ericmedvet** [comment]
Ok. Actually, these are three independent things.
The second one should already work.
The first and third one might be "addressed" at the same time with something like this:
```
(nicknames = [jack; jim; tom]) * [dog(age = 16; nicknames = [simba; goodboy])]
```
giving:
```
[
  dog(age = 16; nicknames = [simba; goodboy; jack]);
  dog(age = 16; nicknames = [simba; goodboy; jim]);
  dog(age = 16; nicknames = [simba; goodboy; tom])
]
```
This would be immediately/automatically extendable to the case:
```
(nicknames = [pippo; pluto]) * (nicknames = [jack; jim; tom]) * [dog(age = 16; nicknames = [simba; goodboy])]
```
that would result in $2 \times 3$ dogs, each one with $4$ nicknames.

**Comment by ericmedvet** [comment]
Moved to [jnb](https://github.com/ericmedvet/jnb): see https://github.com/ericmedvet/jnb/issues/4.
